# Generated by Django 4.2.5 on 2023-10-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_type', models.CharField(max_length=50)),
                ('dish_pic', models.CharField(max_length=100)),
                ('dish_price', models.FloatField()),
                ('dish_qty', models.IntegerField()),
            ],
        ),
    ]
