# Generated by Django 4.2.5 on 2023-10-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_time', models.TimeField()),
                ('order_total_amount', models.FloatField()),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_password', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_phone', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=50)),
                ('staff_address', models.CharField(max_length=50)),
                ('staff_note', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_capacity', models.IntegerField()),
                ('table_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_pic',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_time', models.TimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_amount', models.FloatField()),
                ('payment_state', models.CharField(max_length=20)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_c_dish_qty', models.IntegerField()),
                ('order_c_dish_amount', models.FloatField()),
                ('order_c_note', models.CharField(max_length=50)),
                ('order_c_dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.table'),
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.customer')),
            ],
        ),
    ]
