# Generated by Django 4.2.5 on 2023-10-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0005_alter_menu_dish_pic_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
