# Generated by Django 4.2.5 on 2023-10-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_pic',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
