# Generated by Django 4.2.5 on 2023-10-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0007_remove_image_name_alter_image_id_alter_menu_dish_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
