# Generated by Django 4.2.5 on 2023-10-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0008_alter_image_id_alter_menu_dish_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
