# Generated by Django 4.2.4 on 2023-10-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0010_rename_customer_id_customerdetail_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
    ]
