# Generated by Django 4.2.4 on 2023-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0011_delete_customerdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='order created', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total_amount',
            field=models.FloatField(default=0),
        ),
    ]
