# Generated by Django 4.2.4 on 2023-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0012_remove_order_order_time_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.BooleanField(default=False),
        ),
    ]
