# Generated by Django 4.2.4 on 2023-10-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0013_alter_table_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_table',
            field=models.IntegerField(),
        ),
    ]
