# Generated by Django 4.2.5 on 2023-10-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0018_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
