# Generated by Django 4.2.5 on 2023-10-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0019_table_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
