# Generated by Django 4.2.5 on 2023-10-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0020_order_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish_pic',
        ),
    ]
