# Generated by Django 4.2.5 on 2023-10-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0023_rename_order_c_dish_ordercontent_dish_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_state',
        ),
    ]
