# Generated by Django 4.2.5 on 2023-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0025_alter_ordercontent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_order',
            field=models.CharField(max_length=100),
        ),
    ]
