# Generated by Django 4.2.6 on 2023-10-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0031_alter_menu_dish_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expire_date', models.CharField(max_length=5)),
                ('cvv_number', models.CharField(max_length=3)),
            ],
        ),
    ]
